stages:
  download:
    cmd: python download_images.py
    outs:
      - data/images/

  augment:
    cmd: python augment_images.py
    deps:
      - data/images/
    outs:
      - data/augmented/

  train:
    cmd: python train_cnn.py
    deps:
      - data/augmented/
      - train_cnn.py
    outs:
      - models/cnn_model.h5
      - logs/train_log.json

  evaluate:
    cmd: python evaluate_model.py
    deps:
      - models/cnn_model.h5
      - data/augmented/
    outs:
      - reports/metrics.json
