stages:
  collect:
    cmd: python collect_data.py
    outs:
      - data/raw_data.csv
  preprocess:
    cmd: python preprocess_data.py
    deps:
      - data/raw_data.csv
    outs:
      - data/processed_data.csv
  train:
    cmd: python train_model.py
    deps:
      - data/processed_data.csv
    outs:
      - models/model.pkl